var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},h="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");h=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?h=self.location.href:"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src),h=h.startsWith("blob:")?"":h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==
d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var na=f.print||console.log.bind(console),n=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);f.quit&&(ha=f.quit);var q;f.wasmBinary&&(q=f.wasmBinary);var oa,r=!1,t,u,w,pa,qa,x,y,ra,z;
function sa(){var a=oa.buffer;f.HEAP8=u=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=w=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=x=new Int32Array(a);f.HEAPU32=y=new Uint32Array(a);f.HEAPF32=ra=new Float32Array(a);f.HEAPF64=z=new Float64Array(a)}var ta=[],ua=[],va=[],wa=[];function xa(){var a=f.preRun.shift();ta.unshift(a)}var A=0,ya=null,C=null;
function za(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);r=!0;t=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Ba;function Ca(a){if(a==Ba&&q)return new Uint8Array(q);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Da(a){return q?Promise.resolve().then(()=>Ca(a)):ia(a).then(b=>new Uint8Array(b),()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{n(`failed to asynchronously prepare wasm: ${d}`);za(d)})}function Fa(a,b){var c=Ba;q||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||la(c)||ca||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){n(`wasm streaming compile failed: ${e}`);n("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}
function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ga=a=>{for(;0<a.length;)a.shift()(f)},Ha=f.noExitRuntime||!0,Ia="undefined"!=typeof TextDecoder?new TextDecoder:void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Qa=(a,b)=>{Ja=a;Ka=b;if(E)if(La||=!0,0==a)F=function(){var d=Math.max(0,Ma+b-Na())|0;setTimeout(G,d)};else if(1==a)F=function(){Oa(G)};else if(2==a){if("undefined"==typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=function(d){c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);
postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;F=function(){Pa(G)}}},Na;Na=()=>performance.now();
var Ya=(a,b,c,d,e)=>{E=a;Ra=d;var k=H;La=!1;G=function(){if(!r)if(0<Sa.length){var g=Sa.shift();g.Yc(g.Tc);if(Ta){var l=Ta,m=0==l%1?l-1:Math.floor(l);Ta=g.Vc?m:(8*l+(m+.5))/9}f.setStatus&&(g=f.statusMessage||"Please wait...",l=Ta,m=Ua.Xc,l?l<m?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(g):f.setStatus(""));k<H||setTimeout(G,0)}else if(!(k<H))if(Va=Va+1|0,1==Ja&&1<Ka&&0!=Va%Ka)F();else{0==Ja&&(Ma=Na());if(!(r||f.preMainLoop&&!1===f.preMainLoop())){if(!r)try{if(a(),!Ha)try{t=
g=t,Wa(g)}catch(p){Xa(p)}}catch(p){Xa(p)}f.postMainLoop?.()}k<H||("object"==typeof SDL&&SDL.audio?.bd?.(),F())}};e||(b&&0<b?Qa(0,1E3/b):Qa(1,1),F());if(c)throw"unwind";},Xa=a=>{a instanceof ma||"unwind"==a||ha(1,a)},Wa=a=>{t=a;Ha||(f.onExit?.(a),r=!0);ha(a,new ma(a))},Za=a=>{t=a;Wa(a)},La=!1,F=null,H=0,E=null,Ra=0,Ja=0,Ka=0,Va=0,Sa=[];function $a(){F=null;H++}var Ua={},Ma,G,Ta,I=!1,ab=!1,bb=[];
function cb(){function a(){ab=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!db){db=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!ab&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}var eb=!1,fb=void 0,J=void 0;
function gb(){if(!I)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var hb=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===hb)hb=b+1E3/60;else for(;b+2>=hb;)hb+=1E3/60;setTimeout(a,Math.max(hb-b,0))}}var ib=[];function jb(){var a=f.canvas;ib.forEach(b=>b(a.width,a.height))}
function kb(a,b,c){b&&c?(a.Rc=b,a.Oc=c):(b=a.Rc,c=a.Oc);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var k=Math.min(screen.width/d,screen.height/e);d=Math.round(d*k);e=Math.round(e*
k)}J?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Pa,db,lb=0,mb=[];
function nb(){if(navigator.userActivation?navigator.userActivation.isActive:lb&&ob.sc){var a=mb;mb=[];for(var b of a)b.jd(...b.Uc)}}var K=[];function pb(a){var b=K[a];b.target.removeEventListener(b.ec,b.Ac,b.fc);K.splice(a,1)}function L(a){if(!a.target)return-4;if(a.hc)a.Ac=function(c){++lb;ob=a;nb();a.ic(c);nb();--lb},a.target.addEventListener(a.ec,a.Ac,a.fc),K.push(a);else for(var b=0;b<K.length;++b)K[b].target==a.target&&K[b].ec==a.ec&&pb(b--);return 0}
function qb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var ob,rb,sb,tb,ub,vb,wb,xb,yb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?D(w,a):"":a;return yb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},zb=a=>0>yb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Ab=[],Bb,O=a=>{var b=Ab[a];b||(a>=Ab.length&&(Ab.length=a+1),Ab[a]=b=Bb.get(a));return b},P=(a,b,c)=>{var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var l=
a.charCodeAt(++k);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Cb=(a,b,c,d,e,k)=>{rb||=Q(256);a={target:N(a),ec:k,hc:d,ic:(g=event)=>{var l=g.target.id?g.target.id:"",m=rb;P(qb(g.target),m+0,128);P(l,m+128,128);O(d)(e,m,b)&&g.preventDefault()},fc:c};return L(a)},Db=(a,
b,c,d,e,k)=>{sb||=Q(160);a={target:N(a),ec:k,hc:d,ic:g=>{var l=sb;z[l>>3]=g.timeStamp;var m=l>>2;x[m+2]=g.location;u[l+12]=g.ctrlKey;u[l+13]=g.shiftKey;u[l+14]=g.altKey;u[l+15]=g.metaKey;u[l+16]=g.repeat;x[m+5]=g.charCode;x[m+6]=g.keyCode;x[m+7]=g.which;P(g.key||"",l+32,32);P(g.code||"",l+64,32);P(g.char||"",l+96,32);P(g.locale||"",l+128,32);O(d)(e,l,b)&&g.preventDefault()},fc:c};return L(a)},Eb=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;x[d+2]=b.screenX;x[d+3]=b.screenY;x[d+4]=b.clientX;x[d+5]=b.clientY;
u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;x[d+8]=b.movementX;x[d+9]=b.movementY;a=zb(c);x[d+10]=b.clientX-(a.left|0);x[d+11]=b.clientY-(a.top|0)},Fb=(a,b,c,d,e,k)=>{tb||=Q(64);a=N(a);return L({target:a,sc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,ec:k,hc:d,ic:(g=event)=>{Eb(tb,g,a);O(d)(e,tb,b)&&g.preventDefault()},fc:c})},Gb=(a,b,c,d,e)=>{ub||=Q(257);return L({target:a,ec:e,hc:d,ic:(k=event)=>{var g=ub,l=document.pointerLockElement||
document.lc||document.Bc||document.yc;u[g]=!!l;var m=l?.id||"";P(qb(l),g+1,128);P(m,g+129,128);O(d)(20,g,b)&&k.preventDefault()},fc:c})},Hb=(a,b,c,d,e)=>L({target:a,ec:e,hc:d,ic:(k=event)=>{O(d)(38,0,b)&&k.preventDefault()},fc:c}),Ib=(a,b,c,d)=>{vb||=Q(36);a=N(a);return L({target:a,ec:"resize",hc:d,ic:(e=event)=>{if(e.target==a){var k=document.body;if(k){var g=vb;x[g>>2]=0;x[g+4>>2]=k.clientWidth;x[g+8>>2]=k.clientHeight;x[g+12>>2]=innerWidth;x[g+16>>2]=innerHeight;x[g+20>>2]=outerWidth;x[g+24>>2]=
outerHeight;x[g+28>>2]=pageXOffset|0;x[g+32>>2]=pageYOffset|0;O(d)(10,g,b)&&e.preventDefault()}}},fc:c})},Jb=(a,b,c,d,e,k)=>{wb||=Q(1552);a=N(a);return L({target:a,sc:"touchstart"==k||"touchend"==k,ec:k,hc:d,ic:g=>{var l={},m=g.touches;for(var p of m)p.Cc=p.Dc=0,l[p.identifier]=p;for(var v of g.changedTouches)v.Cc=1,l[v.identifier]=v;for(var M of g.targetTouches)l[M.identifier].Dc=1;m=wb;z[m>>3]=g.timeStamp;u[m+12]=g.ctrlKey;u[m+13]=g.shiftKey;u[m+14]=g.altKey;u[m+15]=g.metaKey;p=m+16;v=zb(a);M=0;
for(let B of Object.values(l))if(l=p>>2,x[l]=B.identifier,x[l+1]=B.screenX,x[l+2]=B.screenY,x[l+3]=B.clientX,x[l+4]=B.clientY,x[l+5]=B.pageX,x[l+6]=B.pageY,u[p+28]=B.Cc,u[p+29]=B.Dc,x[l+8]=B.clientX-(v.left|0),x[l+9]=B.clientY-(v.top|0),p+=48,31<++M)break;x[m+8>>2]=M;O(d)(e,m,b)&&g.preventDefault()},fc:c})},Kb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=
(c,d,e,k,g)=>b.drawElementsInstancedANGLE(c,d,e,k,g))},Lb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Mb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Nb=a=>{a.Wc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Ob=a=>{a.Zc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},
Pb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Qb=1,Rb=[],R=[],Sb=[],Tb=[],S=[],T=[],Ub=[],Vb=[],U=[],Wb={},Xb=4,Yb=0,Zb=a=>{for(var b=Qb++,c=a.length;c<b;c++)a[c]=null;return b},X=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=V[c](),g=k&&Zb(d);k?(k.name=g,d[g]=k):W||=1282;x[b+4*e>>2]=g}},ac=(a,b)=>{a.lc||(a.lc=a.getContext,a.getContext=function(d,e){e=a.lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.uc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
$b(c,b):0},$b=(a,b)=>{var c=Zb(Vb),d={handle:c,attributes:b,version:b.uc,oc:a};a.canvas&&(a.canvas.Sc=d);Vb[c]=d;("undefined"==typeof b.zc||b.zc)&&bc(d);return c},cc=a=>{Y=Vb[a];f.tc=V=Y?.oc;return!(a&&!V)},bc=a=>{a||=Y;if(!a.Pc){a.Pc=!0;var b=a.oc;Kb(b);Lb(b);Mb(b);Nb(b);Ob(b);2<=a.version&&(b.xc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.xc)b.xc=b.getExtension("EXT_disjoint_timer_query");b.Qc=b.getExtension("WEBGL_multi_draw");Pb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},dc={},W,Y,ec=(a,b,c,d,e,k)=>{a={target:N(a),ec:k,hc:d,ic:(g=event)=>{O(d)(e,0,b)&&g.preventDefault()},fc:c};L(a)},fc=(a,b,c,d)=>{xb||=Q(96);return L({target:a,sc:!0,ec:"wheel",hc:d,ic:(e=event)=>{var k=xb;Eb(k,e,a);z[k+64>>3]=e.deltaX;z[k+72>>3]=e.deltaY;z[k+80>>3]=e.deltaZ;x[k+88>>2]=e.deltaMode;O(d)(9,k,b)&&e.preventDefault()},fc:c})},gc=["default","low-power","high-performance"],hc=[null,[],[]],ic=[];
function jc(){var a=Pb(V);return a=a.concat(a.map(b=>"GL_"+b))}
var kc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){W||=1282;return}c=jc().length;break;case 33307:case 33308:if(2>Y.version){W||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:W||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:W||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}x[b>>2]=c}else W||=1281},lc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},mc=a=>{var b=lc(a)+1,c=Q(b);c&&P(a,c,b);return c},nc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),oc=a=>{a-=5120;return 0==a?u:1==a?w:2==a?pa:4==a?x:6==a?ra:5==a||28922==a||28520==a||30779==a||30782==a?y:qa},pc=(a,b,c,d,e)=>{a=oc(a);b=d*((Yb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Xb-1&-Xb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},rc=a=>{var b=lc(a)+1,c=qc(b);P(a,c,b);return c},uc=a=>{var b=sc();a();tc(b)};
f.requestFullscreen=function(a,b){function c(){I=!1;var k=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===k?(d.exitFullscreen=gb,fb&&d.requestPointerLock(),I=!0,J?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),kb(f.canvas),jb()):kb(d)):(k.parentNode.insertBefore(d,k),k.parentNode.removeChild(k),J?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>
2]&-8388609),kb(f.canvas),jb()):kb(d));f.onFullScreen?.(I);f.onFullscreen?.(I)}fb=a;J=b;"undefined"==typeof fb&&(fb=!0);"undefined"==typeof J&&(J=!1);var d=f.canvas;eb||(eb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.requestAnimationFrame=Oa;f.setCanvasSize=function(a,b,c){kb(f.canvas,a,b);c||jb()};f.pauseMainLoop=$a;f.resumeMainLoop=function(){H++;var a=Ja,b=Ka,c=E;E=null;Ya(c,0,!1,Ra,!0);Qa(a,b);F()};
f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=function(a,b,c,d){if(b&&f.tc&&a==f.canvas)return f.tc;var e;if(b){var k={antialias:!1,alpha:!1,uc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)k[g]=d[g];if("undefined"!=typeof dc&&(e=ac(a,k)))var l=Vb[e].oc}else l=a.getContext("2d");if(!l)return null;c&&(f.tc=l,b&&cc(e),f.kd=b,bb.forEach(m=>m()),cb());return l};
for(var V,vc=0;32>vc;++vc)ic.push(Array(vc));
var Gc={lb:()=>{za("")},hb:(a,b,c)=>w.copyWithin(a,b,b+c),gb:a=>{if(ca){if(!a)return 1;a=a?D(w,a):"";if(!a.length)return 0;a=require("child_process").hd(a,[],{dd:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15}return 2})(a.signal)):a.status<<8|0}return a?-52:0},Ua:()=>{$a();E=null},da:()=>"number"==typeof devicePixelRatio&&
devicePixelRatio||1,fa:(a,b,c)=>{a=N(a);if(!a)return-4;a=zb(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},Va:()=>performance.now(),$a:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},fb:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);sa();var k=1;break a}catch(g){}k=
void 0}if(k)return!0}return!1},N:(a,b,c,d)=>Cb(a,b,c,d,12,"blur"),ca:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},O:(a,b,c,d)=>Cb(a,b,c,d,13,"focus"),X:(a,b,c,d)=>Db(a,b,c,d,2,"keydown"),V:(a,b,c,d)=>Db(a,b,c,d,1,"keypress"),W:(a,b,c,d)=>Db(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=O(a);Ya(a,b,c)},ba:(a,b,c,d)=>Fb(a,b,c,d,5,"mousedown"),_:(a,b,c,d)=>Fb(a,b,c,d,33,"mouseenter"),Z:(a,b,c,d)=>Fb(a,b,c,d,34,"mouseleave"),$:(a,b,c,d)=>Fb(a,b,c,d,8,"mousemove"),aa:(a,b,c,d)=>Fb(a,b,c,d,6,"mouseup"),
Q:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.lc||document.body.Bc||document.body.yc))return-1;a=N(a);if(!a)return-4;Gb(a,b,c,d,"mozpointerlockchange");Gb(a,b,c,d,"webkitpointerlockchange");Gb(a,b,c,d,"mspointerlockchange");return Gb(a,b,c,d,"pointerlockchange")},P:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.lc||document.body.Bc||document.body.yc))return-1;a=N(a);if(!a)return-4;Hb(a,b,c,d,"mozpointerlockerror");Hb(a,b,
c,d,"webkitpointerlockerror");Hb(a,b,c,d,"mspointerlockerror");return Hb(a,b,c,d,"pointerlockerror")},ea:(a,b,c,d)=>Ib(a,b,c,d),R:(a,b,c,d)=>Jb(a,b,c,d,25,"touchcancel"),S:(a,b,c,d)=>Jb(a,b,c,d,23,"touchend"),T:(a,b,c,d)=>Jb(a,b,c,d,24,"touchmove"),U:(a,b,c,d)=>Jb(a,b,c,d,22,"touchstart"),M:(a,b,c,d)=>{ec(a,b,c,d,31,"webglcontextlost");return 0},L:(a,b,c,d)=>{ec(a,b,c,d,32,"webglcontextrestored");return 0},Y:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?fc(a,b,c,d):-1:-4,_a:(a,b)=>{var c=b>>2;
b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+5],powerPreference:gc[x[c+2]],failIfMajorPerformanceCaveat:!!u[b+12],uc:x[c+4],$c:x[c+5],zc:u[b+24],Nc:u[b+25],ad:x[c+7],cd:u[b+32]};a=N(a);return!a||b.Nc?0:ac(a,b)},Ya:(a,b)=>{a=Vb[a];b=b?D(w,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Kb(V);"OES_vertex_array_object"==b&&Lb(V);"WEBGL_draw_buffers"==b&&Mb(V);"WEBGL_draw_instanced_base_vertex_base_instance"==
b&&Nb(V);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Ob(V);"WEBGL_multi_draw"==b&&(V.Qc=V.getExtension("WEBGL_multi_draw"));return!!a.oc.getExtension(b)},Za:a=>cc(a)?0:-5,Lb:Za,ib:()=>52,eb:function(){return 70},jb:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var g=y[b>>2],l=y[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=w[g+m],v=hc[a];0===p||10===p?((1===a?na:n)(D(v,0)),v.length=0):v.push(p)}e+=l}y[d>>2]=e;return 0},i:a=>V.activeTexture(a),ua:(a,b)=>{V.attachShader(R[a],T[b])},b:(a,b)=>{35051==
a?V.wc=b:35052==a&&(V.kc=b);V.bindBuffer(a,Rb[b])},a:(a,b,c)=>{V.bindBufferBase(a,b,Rb[c])},j:(a,b)=>{V.bindFramebuffer(a,Sb[b])},Ga:(a,b)=>{V.bindRenderbuffer(a,Tb[b])},h:(a,b)=>{V.bindSampler(a,U[b])},c:(a,b)=>{V.bindTexture(a,S[b])},K:a=>{V.bindVertexArray(Ub[a])},G:(a,b,c,d)=>V.blendColor(a,b,c,d),H:(a,b)=>V.blendEquationSeparate(a,b),I:(a,b,c,d)=>V.blendFuncSeparate(a,b,c,d),pb:(a,b,c,d,e,k,g,l,m,p)=>V.blitFramebuffer(a,b,c,d,e,k,g,l,m,p),Ia:(a,b,c,d)=>{2<=Y.version?c&&b?V.bufferData(a,w,d,c,
b):V.bufferData(a,b,d):V.bufferData(a,c?w.subarray(c,c+b):b,d)},z:(a,b,c,d)=>{2<=Y.version?c&&V.bufferSubData(a,b,w,d,c):V.bufferSubData(a,b,w.subarray(d,d+c))},oa:a=>V.checkFramebufferStatus(a),zb:(a,b,c,d)=>V.clearBufferfi(a,b,c,d),ka:(a,b,c)=>{V.clearBufferfv(a,b,ra,c>>2)},yb:(a,b,c)=>{V.clearBufferiv(a,b,x,c>>2)},n:(a,b,c,d)=>{V.colorMask(!!a,!!b,!!c,!!d)},Eb:a=>{V.compileShader(T[a])},Aa:(a,b,c,d,e,k,g,l)=>{2<=Y.version?V.kc||!g?V.compressedTexImage2D(a,b,c,d,e,k,g,l):V.compressedTexImage2D(a,
b,c,d,e,k,w,l,g):V.compressedTexImage2D(a,b,c,d,e,k,l?w.subarray(l,l+g):null)},ya:(a,b,c,d,e,k,g,l,m)=>{V.kc?V.compressedTexImage3D(a,b,c,d,e,k,g,l,m):V.compressedTexImage3D(a,b,c,d,e,k,g,w,m,l)},va:()=>{var a=Zb(R),b=V.createProgram();b.name=a;b.rc=b.pc=b.qc=0;b.vc=1;R[a]=b;return a},Gb:a=>{var b=Zb(T);T[b]=V.createShader(a);return b},D:a=>V.cullFace(a),La:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Rb[d];e&&(V.deleteBuffer(e),e.name=0,Rb[d]=null,d==V.wc&&(V.wc=0),d==V.kc&&(V.kc=0))}},l:(a,
b)=>{for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Sb[d];e&&(V.deleteFramebuffer(e),e.name=0,Sb[d]=null)}},q:a=>{if(a){var b=R[a];b?(V.deleteProgram(b),b.name=0,R[a]=null):W||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Tb[d];e&&(V.deleteRenderbuffer(e),e.name=0,Tb[d]=null)}},A:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=U[d];e&&(V.deleteSampler(e),e.name=0,U[d]=null)}},w:a=>{if(a){var b=T[a];b?(V.deleteShader(b),T[a]=null):W||=1281}},C:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],
e=S[d];e&&(V.deleteTexture(e),e.name=0,S[d]=null)}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2];V.deleteVertexArray(Ub[d]);Ub[d]=null}},t:a=>V.depthFunc(a),s:a=>{V.depthMask(!!a)},e:a=>V.disable(a),J:a=>{V.disableVertexAttribArray(a)},rb:(a,b,c)=>{V.drawArrays(a,b,c)},sb:(a,b,c,d)=>{V.drawArraysInstanced(a,b,c,d)},na:(a,b)=>{for(var c=ic[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];V.drawBuffers(c)},tb:(a,b,c,d)=>{V.drawElements(a,b,c,d)},ub:(a,b,c,d,e)=>{V.drawElementsInstanced(a,b,c,d,e)},g:a=>V.enable(a),
vb:a=>{V.enableVertexAttribArray(a)},pa:(a,b,c,d)=>{V.framebufferRenderbuffer(a,b,c,Tb[d])},k:(a,b,c,d,e)=>{V.framebufferTexture2D(a,b,c,S[d],e)},v:(a,b,c,d,e)=>{V.framebufferTextureLayer(a,b,S[c],d,e)},E:a=>V.frontFace(a),Ja:(a,b)=>{X(a,b,"createBuffer",Rb)},qa:(a,b)=>{X(a,b,"createFramebuffer",Sb)},Ha:(a,b)=>{X(a,b,"createRenderbuffer",Tb)},wa:(a,b)=>{X(a,b,"createSampler",U)},Ea:(a,b)=>{X(a,b,"createTexture",S)},Sa:(a,b)=>{X(a,b,"createVertexArray",Ub)},Bb:(a,b)=>V.getAttribLocation(R[a],b?D(w,
b):""),d:(a,b)=>kc(a,b),Hb:(a,b,c,d)=>{a=V.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?P(a,d,b):0;c&&(x[c>>2]=b)},ta:(a,b,c)=>{if(c)if(a>=Qb)W||=1281;else if(a=R[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.rc)for(b=0;b<V.getProgramParameter(a,35718);++b)a.rc=Math.max(a.rc,V.getActiveUniform(a,b).name.length+1);x[c>>2]=a.rc}else if(35722==b){if(!a.pc)for(b=0;b<V.getProgramParameter(a,35721);++b)a.pc=Math.max(a.pc,
V.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.pc}else if(35381==b){if(!a.qc)for(b=0;b<V.getProgramParameter(a,35382);++b)a.qc=Math.max(a.qc,V.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.qc}else x[c>>2]=V.getProgramParameter(a,b);else W||=1281},Cb:(a,b,c,d)=>{a=V.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?P(a,d,b):0;c&&(x[c>>2]=b)},ra:(a,b,c)=>{c?35716==b?(a=V.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(T[a]),
x[c>>2]=a?a.length+1:0):x[c>>2]=V.getShaderParameter(T[a],b):W||=1281},Qa:(a,b)=>{if(2>Y.version)return W||=1282,0;var c=Wb[a];if(c)return 0>b||b>=c.length?(W||=1281,0):c[b];switch(a){case 7939:return c=jc().map(mc),c=Wb[a]=c,0>b||b>=c.length?(W||=1281,0):c[b];default:return W||=1280,0}},o:(a,b)=>{b=b?D(w,b):"";if(a=R[a]){var c=a,d=c.nc,e=c.Lc,k;if(!d)for(c.nc=d={},c.Kc={},k=0;k<V.getProgramParameter(c,35718);++k){var g=V.getActiveUniform(c,k);var l=g.name;g=g.size;var m=nc(l);m=0<m?l.slice(0,m):
l;var p=c.vc;c.vc+=g;e[m]=[g,p];for(l=0;l<g;++l)d[p]=l,c.Kc[p++]=m}c=a.nc;d=0;e=b;k=nc(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Lc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else W||=1281;return-1},ob:(a,b,c)=>{for(var d=ic[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];V.invalidateFramebuffer(a,d)},Ib:a=>{a=R[a];V.linkProgram(a);a.nc=0;a.Lc={}},Ra:(a,b)=>{3317==a?Xb=b:3314==a&&(Yb=b);V.pixelStorei(a,b)},F:(a,b)=>V.polygonOffset(a,b),qb:a=>V.readBuffer(a),Fa:(a,b,c,
d,e)=>V.renderbufferStorageMultisample(a,b,c,d,e),x:(a,b,c)=>{V.samplerParameterf(U[a],b,c)},f:(a,b,c)=>{V.samplerParameteri(U[a],b,c)},Ab:(a,b,c,d)=>V.scissor(a,b,c,d),Fb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var g=(g=y[c+4*k>>2])?D(w,g,d?y[d+4*k>>2]:void 0):"";e+=g}V.shaderSource(T[a],e)},Pa:(a,b,c)=>V.stencilFunc(a,b,c),ja:(a,b,c,d)=>V.stencilFuncSeparate(a,b,c,d),r:a=>V.stencilMask(a),Na:(a,b,c)=>V.stencilOp(a,b,c),ia:(a,b,c,d)=>V.stencilOpSeparate(a,b,c,d),za:(a,b,c,d,e,k,g,l,m)=>{if(2<=Y.version){if(V.kc){V.texImage2D(a,
b,c,d,e,k,g,l,m);return}if(m){var p=oc(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);V.texImage2D(a,b,c,d,e,k,g,l,p,m);return}}p=m?pc(l,g,d,e,m):null;V.texImage2D(a,b,c,d,e,k,g,l,p)},xa:(a,b,c,d,e,k,g,l,m,p)=>{if(V.kc)V.texImage3D(a,b,c,d,e,k,g,l,m,p);else if(p){var v=oc(m);V.texImage3D(a,b,c,d,e,k,g,l,m,v,p>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else V.texImage3D(a,b,c,d,e,k,g,l,m,null)},Da:(a,b,c)=>V.texParameteri(a,b,c),Ca:(a,b,c,d,e)=>V.texStorage2D(a,b,c,d,e),Ba:(a,b,c,d,e,k)=>V.texStorage3D(a,b,
c,d,e,k),nb:(a,b,c,d,e,k,g,l,m)=>{if(2<=Y.version){if(V.kc){V.texSubImage2D(a,b,c,d,e,k,g,l,m);return}if(m){var p=oc(l);V.texSubImage2D(a,b,c,d,e,k,g,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?pc(l,g,e,k,m):null;V.texSubImage2D(a,b,c,d,e,k,g,l,m)},mb:(a,b,c,d,e,k,g,l,m,p,v)=>{if(V.kc)V.texSubImage3D(a,b,c,d,e,k,g,l,m,p,v);else if(v){var M=oc(p);V.texSubImage3D(a,b,c,d,e,k,g,l,m,p,M,v>>>31-Math.clz32(M.BYTES_PER_ELEMENT))}else V.texSubImage3D(a,b,c,d,e,k,g,l,m,p,null)},sa:(a,b)=>{var c=
V,d=c.uniform1i;var e=V.Mc;if(e){var k=e.nc[a];"number"==typeof k&&(e.nc[a]=k=V.getUniformLocation(e,e.Kc[a]+(0<k?`[${k}]`:"")));a=k}else W||=1282,a=void 0;d.call(c,a,b)},m:a=>{a=R[a];V.useProgram(a);V.Mc=a},wb:(a,b)=>{V.vertexAttribDivisor(a,b)},xb:(a,b,c,d,e,k)=>{V.vertexAttribPointer(a,b,c,!!d,e,k)},la:(a,b,c,d)=>V.viewport(a,b,c,d),Kb:function(){f.Ec=a=>{0!=wc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Ec)},Xa:function(){f.Jc=a=>{const b=a.clipboardData.getData("text");
uc(()=>{const c=rc(b);xc(c)})};window.addEventListener("paste",f.Jc)},Ta:function(a){f.ed=[];a=a?D(w,a):"";a=document.getElementById(a);f.Fc=b=>{b.stopPropagation();b.preventDefault()};f.Gc=b=>{b.stopPropagation();b.preventDefault()};f.Hc=b=>{b.stopPropagation();b.preventDefault()};f.Ic=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.gd=c;yc(c.length);for(let e=0;e<c.length;e++)uc(()=>{const k=rc(c[e].name);zc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&
(d|=4);b.metaKey&&(d|=8);Ac(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Fc,!1);a.addEventListener("dragleave",f.Gc,!1);a.addEventListener("dragover",f.Hc,!1);a.addEventListener("drop",f.Ic,!1)},Jb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},y:function(){document.exitPointerLock&&document.exitPointerLock()},Ma:function(a){a=a?D(w,a):"";f.mc=document.getElementById(a);f.mc||console.log("sokol_app.h: invalid target:"+a);f.mc.requestPointerLock||
console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},bb:function(){window.removeEventListener("beforeunload",f.Ec)},Wa:function(){window.removeEventListener("paste",f.Jc)},Oa:function(a){a=a?D(w,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",f.Fc);a.removeEventListener("dragleave",f.Gc);a.removeEventListener("dragover",f.Hc);a.removeEventListener("drop",f.Ic)},p:function(){f.mc&&f.mc.requestPointerLock&&f.mc.requestPointerLock()},Db:function(a,b,c){const d=
document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(w.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},cb:function(){return f.jc?f.jc.bufferSize:0},kb:function(a,b,c){f.dc=null;f.jc=null;"undefined"!==typeof AudioContext?f.dc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.dc=null,console.log("sokol_audio.h: no WebAudio support"));
return f.dc?(console.log("sokol_audio.h: sample rate ",f.dc.sampleRate),f.jc=f.dc.createScriptProcessor(c,0,b),f.jc.onaudioprocess=d=>{const e=d.outputBuffer.length,k=Bc(e);if(k){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=ra[(k>>2)+(g*p+l)]}}},f.jc.connect(f.dc.destination),a=()=>{f.dc&&"suspended"===f.dc.state&&f.dc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},db:function(){return f.dc?f.dc.sampleRate:0},ha:function(){const a=f.dc;null!==a&&(f.jc&&f.jc.disconnect(),a.close(),f.dc=null,f.jc=null)},u:function(a,b,c,d,e,k){b=b?D(w,b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const l=0<d;l&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!l){const m=new Uint8Array(g.response),
p=m.length;p<=k?(w.set(m,e),Cc(a,d,p)):Dc(a)}else Ec(a,g.status)};g.send()},ma:function(a,b){b=b?D(w,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Fc(a,d)}else Ec(a,c.status)};c.send()},ga:function(a,b){b=b?D(w,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=
c.exports;oa=Z.Mb;sa();Bb=Z.$b;ua.unshift(Z.Nb);A--;f.monitorRunDependencies?.(A);0==A&&(null!==ya&&(clearInterval(ya),ya=null),C&&(c=C,C=null,c()));return Z}var b={a:Gc};A++;f.monitorRunDependencies?.(A);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ba||=Aa("doom.wasm")?"doom.wasm":f.locateFile?f.locateFile("doom.wasm",h):h+"doom.wasm";Fa(b,function(c){a(c.instance)});return{}}(),Q=a=>(Q=Z.Ob)(a),xc=f.__sapp_emsc_onpaste=
a=>(xc=f.__sapp_emsc_onpaste=Z.Pb)(a),wc=f.__sapp_html5_get_ask_leave_site=()=>(wc=f.__sapp_html5_get_ask_leave_site=Z.Qb)(),yc=f.__sapp_emsc_begin_drop=a=>(yc=f.__sapp_emsc_begin_drop=Z.Rb)(a),zc=f.__sapp_emsc_drop=(a,b)=>(zc=f.__sapp_emsc_drop=Z.Sb)(a,b),Ac=f.__sapp_emsc_end_drop=(a,b,c)=>(Ac=f.__sapp_emsc_end_drop=Z.Tb)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Ub)(a,b,c,d,e,k,g,l);
var Hc=f._main=(a,b)=>(Hc=f._main=Z.Vb)(a,b),Fc=f.__sfetch_emsc_head_response=(a,b)=>(Fc=f.__sfetch_emsc_head_response=Z.Wb)(a,b),Cc=f.__sfetch_emsc_get_response=(a,b,c)=>(Cc=f.__sfetch_emsc_get_response=Z.Xb)(a,b,c),Ec=f.__sfetch_emsc_failed_http_status=(a,b)=>(Ec=f.__sfetch_emsc_failed_http_status=Z.Yb)(a,b),Dc=f.__sfetch_emsc_failed_buffer_too_small=a=>(Dc=f.__sfetch_emsc_failed_buffer_too_small=Z.Zb)(a),Bc=f.__saudio_emsc_pull=a=>(Bc=f.__saudio_emsc_pull=Z._b)(a),tc=a=>(tc=Z.ac)(a),qc=a=>(qc=
Z.bc)(a),sc=()=>(sc=Z.cc)(),Ic;C=function Jc(){Ic||Kc();Ic||(C=Jc)};function Lc(a=[]){var b=Hc;a.unshift(fa);var c=a.length,d=qc(4*(c+1)),e=d;a.forEach(g=>{y[e>>2]=rc(g);e+=4});y[e>>2]=0;try{var k=b(c,d);Za(k,!0)}catch(g){Xa(g)}}
function Kc(){var a=ea;function b(){if(!Ic&&(Ic=!0,f.calledRun=!0,!r)){Ga(ua);Ga(va);f.onRuntimeInitialized?.();Mc&&Lc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();wa.unshift(c)}Ga(wa)}}if(!(0<A)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();Ga(ta);0<A||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Mc=!0;f.noInitialRun&&(Mc=!1);Kc();
