var g;g||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,r,la=a=>a.startsWith("file://");
function na(){var a=oa.buffer;u=new Int8Array(a);pa=new Int16Array(a);v=new Uint8Array(a);qa=new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);y=new Float32Array(a);z=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function ra(a){g.onAbort?.(a);a=`Aborted(${a})`;k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var pa,w,u,y,z,qa,x,v,xa=a=>{for(;0<a.length;)a.shift()(g)},ya=[],za=[],Aa=()=>{var a=g.preRun.shift();za.push(a)},A=0,B=null,Ba=!0,Ca=0,Da=globalThis.TextDecoder&&new TextDecoder,C=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Da)return Da.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):
(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},F={},Ea=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Fa=a=>{r=a;Ba||0<Ca||(g.onExit?.(a),p=!0);fa(a,new wa(a))},Ga=()=>{if(!(Ba||0<Ca))try{var a=r;r=a;Fa(a)}catch(b){Ea(b)}},Ha=a=>{if(!p)try{a()}catch(b){Ea(b)}finally{Ga()}},Pa=(a,b)=>{Ia=a;Ja=b;if(G)if(Ka||=!0,0==a)H=function(){setTimeout(La,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)H=function(){Na(La)};else{if(!Oa)if(globalThis.setImmediate)Oa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Oa(La)}}},Ya=(a,b,c,d,e)=>{function h(){return f<Qa?(Ga(),!1):!0}G=a;Ra=d;var f=Qa;Ka=!1;La=function(){if(!p)if(0<Sa.length){var l=Sa.shift();l.Hd(l.vd);if(Ta){var n=
Ta,q=0==n%1?n-1:Math.floor(n);Ta=l.yd?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Ta??0,q=Ua.Ed??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(La,0)}else if(h())if(Va=Va+1|0,1==Ia&&1<Ja&&0!=Va%Ja)H();else{0==Ia&&(Ma=performance.now());a:if(!p){for(l of Wa)if(!1===l())break a;Ha(a);for(n of Xa)n()}h()&&H()}};e||(0<b?Pa(0,1E3/b):Pa(1,1),H());if(c)throw"unwind";},Ka=!1,H=null,Qa=0,G=null,Ra=0,Ia=0,Ja=0,Va=
0,Sa=[],Wa=[],Xa=[];function Za(){H=null;Qa++}var $a=0;function Na(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===$a)$a=b+1E3/60;else for(;b+2>=$a;)$a+=1E3/60;setTimeout(a,Math.max($a-b,0))}}var Ua={},Ma,La,Oa,Ta,ab=[0,globalThis.document??0,globalThis.window??0],I=a=>{a=2<a?a?C(v,a):"":a;return ab[a]||globalThis.document?.querySelector(a)},bb=a=>0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},cb=[],J=a=>{var b=cb[a];b||(cb[a]=b=db.get(a));return b};
function eb(a){var b=K.uc[a];b.target.removeEventListener(b.tc,b.$c,b.xc);K.uc.splice(a,1)}function fb(){if(navigator.userActivation?navigator.userActivation.isActive:K.Nc&&K.pd.Kc){var a=K.Cc;K.Cc=[];for(var b of a)b.Qc(...b.Wc)}}function L(a){if(!a.target)return-4;if(a.vc)a.$c=function(c){++K.Nc;K.pd=a;fb();a.zc(c);fb();--K.Nc},a.target.addEventListener(a.tc,a.$c,a.xc),K.uc.push(a);else for(var b=0;b<K.uc.length;++b)K.uc[b].target==a.target&&K.uc[b].tc==a.tc&&eb(b--);return 0}
function gb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={wd:0,Id:0,Oc:0,Ic:0,Uc:0,Sc:0,Lc:0,Cd:0,Md:0,Bd:0,Mc:0,Pc:0,Yd:0,Rc:0,Od(){for(;K.uc.length;)eb(K.uc.length-1);K.Cc=[]},Nc:0,Cc:[],Ad(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of K.Cc)if(e.Qc==a&&d(e.Wc,c))return;K.Cc.push({Qc:a,dd:b,Wc:c});K.Cc.sort((h,f)=>h.dd-f.dd)},Qd(a){K.Cc=K.Cc.filter(b=>b.Qc!=a)},uc:[],Pd:(a,b)=>{for(var c=0;c<K.uc.length;++c)K.uc[c].target!=a||b&&b!=K.uc[c].tc||eb(c--)},Rd(a){let b=!1;for(let c=0;c<
K.uc.length;++c){const d=K.uc[c];d.target===a.target&&d.wc===a.wc&&d.vc===a.vc&&d.yc===a.yc&&(eb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.codePointAt(h);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&
63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;h++}}d[b]=0;return b-e},hb=(a,b,c,d,e,h)=>{K.Lc||(K.Lc=N(256));a={target:I(a),tc:h,wc:e,yc:b,vc:d,zc:f=>{var l=f.target.id?f.target.id:"",n=K.Lc;M(gb(f.target),n+0,128);M(l,n+128,128);J(d)(e,n,b)&&f.preventDefault()},xc:c};return L(a)},ib=(a,b,c,d,e)=>{K.Mc||(K.Mc=N(276));return L({target:a,tc:e,wc:19,yc:b,vc:d,zc:h=>{var f=K.Mc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;u[f]=n;u[f+1]=K.fullscreenEnabled();var q=n?l:K.td,t=q?.id||"";M(gb(q),f+2,128);M(t,f+130,128);w[f+260>>2]=q?q.clientWidth:0;w[f+264>>2]=q?q.clientHeight:0;w[f+268>>2]=screen.width;w[f+272>>2]=screen.height;n&&(K.td=l);J(d)(19,f,b)&&h.preventDefault()},xc:c})},jb=(a,b,c,d,e,h)=>{K.Oc||(K.Oc=N(160));a={target:I(a),tc:h,wc:e,yc:b,vc:d,zc:f=>{var l=K.Oc;z[l>>3]=f.timeStamp;var n=l>>2;w[n+2]=f.location;u[l+12]=f.ctrlKey;u[l+13]=
f.shiftKey;u[l+14]=f.altKey;u[l+15]=f.metaKey;u[l+16]=f.repeat;w[n+5]=f.charCode;w[n+6]=f.keyCode;w[n+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);J(d)(e,l,b)&&f.preventDefault()},xc:c};return L(a)},kb=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+
9]=b.movementY;a=bb(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,h)=>{K.Ic||(K.Ic=N(64));a=I(a);return L({target:a,Kc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,tc:h,wc:e,yc:b,vc:d,zc:f=>{kb(K.Ic,f,a);J(d)(e,K.Ic,b)&&f.preventDefault()},xc:c})},mb=(a,b,c,d)=>{K.Pc||(K.Pc=N(257));return L({target:a,tc:"pointerlockchange",wc:20,yc:b,vc:d,zc:e=>{var h=K.Pc,f=document.pointerLockElement;u[h]=!!f;var l=f?.id||"";M(gb(f),h+1,128);M(l,h+129,128);J(d)(20,h,b)&&e.preventDefault()},
xc:c})},nb=(a,b,c,d)=>L({target:a,tc:"pointerlockerror",wc:38,yc:b,vc:d,zc:e=>{J(d)(38,0,b)&&e.preventDefault()},xc:c}),ob=(a,b,c,d)=>{K.Sc||(K.Sc=N(36));a=I(a);return L({target:a,tc:"resize",wc:10,yc:b,vc:d,zc:e=>{if(e.target==a){var h=document.body;if(h){var f=K.Sc;w[f>>2]=0;w[f+4>>2]=h.clientWidth;w[f+8>>2]=h.clientHeight;w[f+12>>2]=innerWidth;w[f+16>>2]=innerHeight;w[f+20>>2]=outerWidth;w[f+24>>2]=outerHeight;w[f+28>>2]=pageXOffset|0;w[f+32>>2]=pageYOffset|0;J(d)(10,f,b)&&e.preventDefault()}}},
xc:c})},pb=(a,b,c,d,e,h)=>{K.Rc||(K.Rc=N(1552));a=I(a);return L({target:a,Kc:"touchstart"==h||"touchend"==h,tc:h,wc:e,yc:b,vc:d,zc:f=>{var l={},n=f.touches;for(var q of n)q.ad=q.cd=0,l[q.identifier]=q;for(var t of f.changedTouches)t.ad=1,l[t.identifier]=t;for(var D of f.targetTouches)l[D.identifier].cd=1;n=K.Rc;z[n>>3]=f.timeStamp;u[n+12]=f.ctrlKey;u[n+13]=f.shiftKey;u[n+14]=f.altKey;u[n+15]=f.metaKey;q=n+16;t=bb(a);D=0;for(let E of Object.values(l))if(l=q>>2,w[l]=E.identifier,w[l+1]=E.screenX,w[l+
2]=E.screenY,w[l+3]=E.clientX,w[l+4]=E.clientY,w[l+5]=E.pageX,w[l+6]=E.pageY,u[q+28]=E.ad,u[q+29]=E.cd,w[l+8]=E.clientX-(t.left|0),w[l+9]=E.clientY-(t.top|0),q+=48,31<++D)break;w[n+8>>2]=D;J(d)(e,n,b)&&f.preventDefault()},xc:c})},O,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},rb=
a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,P=[],Q=[],vb=[],wb=[],R=[],S=[],xb=[],yb=[],T=[],zb={},Ab=4,Bb=0,Cb=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=O[c](),f=h&&Cb(d);h?(h.name=f,d[f]=h):U||=1282;w[b+4*e>>2]=f}},Eb=(a,b)=>{a.ed||(a.ed=a.getContext,a.getContext=function(d,e){e=a.ed(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.bd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Db(c,b):0},Db=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.bd,Vc:a};a.canvas&&(a.canvas.ud=d);yb[c]=d;if("undefined"==typeof b.Zc||b.Zc)if((a=d)||(a=W),!a.sd){a.sd=!0;b=a.Vc;b.Ld=b.getExtension("WEBGL_multi_draw");b.Gd=b.getExtension("EXT_polygon_offset_clamp");b.Fd=b.getExtension("EXT_clip_control");b.Zd=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.Dd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Jd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Yc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Yc)b.Yc=b.getExtension("EXT_disjoint_timer_query");for(var e of tb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},U,W,Fb=(a,b,c,d,e,h)=>{a={target:I(a),tc:h,wc:e,yc:b,vc:d,zc:f=>{J(d)(e,0,b)&&f.preventDefault()},xc:c};L(a)},Gb=(a,b,c,d)=>{K.Uc||(K.Uc=N(96));return L({target:a,Kc:!0,tc:"wheel",wc:9,yc:b,vc:d,zc:e=>{var h=K.Uc;kb(h,e,a);z[h+64>>3]=e.deltaX;z[h+72>>3]=e.deltaY;z[h+
80>>3]=e.deltaZ;w[h+88>>2]=e.deltaMode;J(d)(9,h,b)&&e.preventDefault()},xc:c})},Hb=["default","low-power","high-performance"],Ib=[null,[],[]],Jb=[],Kb=()=>{var a=tb(O);return a=a.concat(a.map(b=>"GL_"+b))},Lb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){U||=1282;return}c=Kb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}c=33307==
a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||
d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else U||=1281},Mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Nb=a=>{var b=Mb(a)+1,c=N(b);c&&M(a,c,b);return c},Ob=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Pb=a=>{a-=5120;return 0==a?u:1==a?v:2==a?pa:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:qa},X=a=>{var b=O.qd;if(b){var c=b.Ec[a];"number"==typeof c&&(b.Ec[a]=c=O.getUniformLocation(b,b.nd[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Y=[],Qb=[],Sb=a=>{var b=Mb(a)+1,c=Rb(b);M(a,c,b);return c},Vb=a=>{var b=Tb();a();Ub(b)};g.requestAnimationFrame=Na;g.pauseMainLoop=Za;
g.resumeMainLoop=function(){Qa++;var a=Ia,b=Ja,c=G;G=null;Ya(c,0,!1,Ra,!0);Pa(a,b);H()};g.preMainLoop&&Wa.push(g.preMainLoop);g.postMainLoop&&Xa.push(g.postMainLoop);for(let a=0;32>a;++a)Jb.push(Array(a));for(var Wb=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=Wb.subarray(0,Z);var Xb=new Int32Array(288);for(Z=0;288>=Z;++Z)Qb[Z]=Xb.subarray(0,Z);g.noExitRuntime&&(Ba=g.noExitRuntime);g.print&&(ma=g.print);g.printErr&&(k=g.printErr);g.wasmBinary&&(m=g.wasmBinary);g.arguments&&(da=g.arguments);
g.thisProgram&&(ea=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,N,jc,Ub,Rb,Tb,oa,db,kc={ib:()=>ra(""),db:()=>{Ba=!1;Ca=0},bb:a=>{if(ca){if(!a)return 1;a=a?C(v,a):"";if(!a.length)return 0;a=require("node:child_process").Wd(a,[],{Td:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15;default:return 2}})(a.signal)):a.status<<8|0}return a?-52:0},$a:(a,
b)=>{F[a]&&(clearTimeout(F[a].id),delete F[a]);if(!b)return 0;var c=setTimeout(()=>{delete F[a];Ha(()=>jc(a,performance.now()))},b);F[a]={id:c,Xd:b};return 0},Pa:()=>{Za();G=null},ha:()=>globalThis.devicePixelRatio??1,ja:(a,b,c)=>{a=I(a);if(!a)return-4;a=bb(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},Ra:()=>performance.now(),Wa:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=
b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);na();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},R:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),ga:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),Q:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;ib(a,b,c,d,"webkitfullscreenchange");return ib(a,b,c,d,"fullscreenchange")},$:(a,
b,c,d)=>jb(a,b,c,d,2,"keydown"),Z:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),_:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),Xa:(a,b,c)=>{a=J(a);Ya(a,b,c)},fa:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),ca:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),ba:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),da:(a,b,c,d)=>lb(a,b,c,d,8,"mousemove"),ea:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),U:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?mb(a,b,c,d):-4:-1,T:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?nb(a,b,c,d):-4:-1,ia:(a,b,c,d)=>ob(a,
b,c,d),V:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),W:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),X:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),Y:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{Fb(a,b,c,d,31,"webglcontextlost");return 0},O:(a,b,c,d)=>{Fb(a,b,c,d,32,"webglcontextrestored");return 0},aa:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Gb(a,b,c,d):-1:-4,Va:(a,b)=>{var c=b>>2;b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+
5],powerPreference:Hb[w[c+2]],failIfMajorPerformanceCaveat:!!u[b+12],bd:w[c+4],Kd:w[c+5],Zc:u[b+24],rd:u[b+25],Nd:w[c+7],Sd:u[b+32]};a=I(a);return!a||b.rd?0:Eb(a,b)},Ua:a=>{W=yb[a];g.ctx=O=W?.Vc;return!a||O?0:-5},jb:a=>{r=a;Fa(a)},fb:()=>52,eb:function(){return 70},gb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=x[b>>2],l=x[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,t=v[f+n],D=Ib[q];0===t||10===t?((1===q?ma:k)(C(D)),D.length=0):D.push(t)}e+=l}x[d>>2]=e;return 0},o:a=>O.activeTexture(a),r:(a,b)=>{O.attachShader(Q[a],
S[b])},a:(a,b)=>{35051==a?O.Xc=b:35052==a&&(O.Dc=b);O.bindBuffer(a,P[b])},v:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},Ab:(a,b,c,d,e)=>{O.bindBufferRange(a,b,P[c],d,e)},h:(a,b)=>{O.bindFramebuffer(a,vb[b])},Lb:(a,b)=>{O.bindRenderbuffer(a,wb[b])},n:(a,b)=>{O.bindSampler(a,T[b])},c:(a,b)=>{O.bindTexture(a,R[b])},N:a=>{O.bindVertexArray(xb[a])},I:(a,b,c,d)=>O.blendColor(a,b,c,d),J:(a,b)=>O.blendEquationSeparate(a,b),K:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),lb:(a,b,c,d,e,h,f,l,n,q)=>O.blitFramebuffer(a,
b,c,d,e,h,f,l,n,q),Ea:(a,b,c,d)=>{2<=W.version?c&&b?O.bufferData(a,v,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?v.subarray(c,c+b):b,d)},C:(a,b,c,d)=>{2<=W.version?c&&O.bufferSubData(a,b,v,d,c):O.bufferSubData(a,b,v.subarray(d,d+c))},Jb:a=>O.checkFramebufferStatus(a),Gb:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{O.clearBufferfv(a,b,y,c>>2)},Fb:(a,b,c)=>{O.clearBufferiv(a,b,w,c>>2)},p:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Qb:a=>{O.compileShader(S[a])},t:(a,b,c,d,e,h,f,l,n)=>{2<=W.version?
O.Dc||!l?O.compressedTexSubImage2D(a,b,c,d,e,h,f,l,n):O.compressedTexSubImage2D(a,b,c,d,e,h,f,v,n,l):O.compressedTexSubImage2D(a,b,c,d,e,h,f,v.subarray(n,n+l))},za:(a,b,c,d,e,h,f,l,n,q,t)=>{O.Dc?O.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,q,t):O.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,v,t,q)},wa:()=>{var a=Cb(Q),b=O.createProgram();b.name=a;b.Hc=b.Fc=b.Gc=0;b.Tc=1;Q[a]=b;return a},Sb:a=>{var b=Cb(S);S[b]=O.createShader(a);return b},F:a=>O.cullFace(a),Ia:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*
c>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=0,P[d]=null,d==O.Xc&&(O.Xc=0),d==O.Dc&&(O.Dc=0))}},u:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=vb[d];e&&(O.deleteFramebuffer(e),e.name=0,vb[d]=null)}},m:a=>{if(a){var b=Q[a];b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=wb[d];e&&(O.deleteRenderbuffer(e),e.name=0,wb[d]=null)}},E:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},k:a=>{if(a){var b=
S[a];b?(O.deleteShader(b),S[a]=null):U||=1281}},i:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];O.deleteVertexArray(xb[d]);xb[d]=null}},y:a=>O.depthFunc(a),x:a=>{O.depthMask(!!a)},d:a=>O.disable(a),L:a=>{O.disableVertexAttribArray(a)},nb:(a,b,c)=>{O.drawArrays(a,b,c)},ob:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},ra:(a,b)=>{for(var c=Jb[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];O.drawBuffers(c)},pb:(a,b,
c,d)=>{O.drawElements(a,b,c,d)},qb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},g:a=>O.enable(a),Bb:a=>{O.enableVertexAttribArray(a)},j:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,wb[d])},e:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,R[d],e)},A:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},G:a=>O.frontFace(a),Fa:(a,b)=>{V(a,b,"createBuffer",P)},M:(a,b)=>{V(a,b,"createFramebuffer",vb)},Mb:(a,b)=>{V(a,b,"createRenderbuffer",wb)},xa:(a,b)=>{V(a,b,"createSampler",T)},Da:(a,b)=>{V(a,b,"createTexture",
R)},Oa:(a,b)=>{V(a,b,"createVertexArray",xb)},Nb:(a,b)=>O.getAttribLocation(Q[a],b?C(v,b):""),b:(a,b)=>Lb(a,b),Ub:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(w[c>>2]=b)},ua:(a,b,c)=>{if(c)if(a>=ub)U||=1281;else if(a=Q[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.Hc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Hc=Math.max(a.Hc,O.getActiveUniform(a,b).name.length+1)}w[c>>
2]=a.Hc}else if(35722==b){if(!a.Fc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.Fc=Math.max(a.Fc,O.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Fc}else if(35381==b){if(!a.Gc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.Gc=Math.max(a.Gc,O.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.Gc}else w[c>>2]=O.getProgramParameter(a,b);else U||=1281},Pb:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(w[c>>2]=b)},sa:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(S[a]),
null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(S[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Ma:(a,b)=>{if(2>W.version)return U||=1282,0;var c=zb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Kb().map(Nb),c=zb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},ta:(a,b)=>{b=b?C(v,b):"";if(a=Q[a]){var c=a,d=c.Ec,e=c.od,h;if(!d){c.Ec=d={};c.nd={};var f=O.getProgramParameter(c,35718);
for(h=0;h<f;++h){var l=O.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Ob(n);q=0<q?n.slice(0,q):n;var t=c.Tc;c.Tc+=l;e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.nd[t++]=q}}c=a.Ec;d=0;e=b;h=Ob(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.od[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=1281;return-1},kb:(a,b,c)=>{for(var d=Jb[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];O.invalidateFramebuffer(a,d)},va:a=>{a=Q[a];O.linkProgram(a);a.Ec=0;a.od={}},Na:(a,b)=>{3317==a?Ab=
b:3314==a&&(Bb=b);O.pixelStorei(a,b)},H:(a,b)=>O.polygonOffset(a,b),mb:a=>O.readBuffer(a),Kb:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),B:(a,b,c)=>{O.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{O.samplerParameteri(T[a],b,c)},Hb:(a,b,c,d)=>O.scissor(a,b,c,d),Rb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=x[c+4*h>>2])?C(v,f,d?x[d+4*h>>2]:void 0):"";e+=f}O.shaderSource(S[a],e)},Ka:(a,b,c)=>O.stencilFunc(a,b,c),oa:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),q:a=>O.stencilMask(a),Ja:(a,b,c)=>
O.stencilOp(a,b,c),na:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Ca:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ba:(a,b,c,d,e,h)=>O.texStorage3D(a,b,c,d,e,h),s:(a,b,c,d,e,h,f,l,n)=>{if(2<=W.version){if(O.Dc){O.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=Pb(l);O.texSubImage2D(a,b,c,d,e,h,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Pb(l);var t=h*((Bb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Ab-1&-Ab);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),
n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,h,f,l,n)},ya:(a,b,c,d,e,h,f,l,n,q,t)=>{if(O.Dc)O.texSubImage3D(a,b,c,d,e,h,f,l,n,q,t);else if(t){var D=Pb(q);O.texSubImage3D(a,b,c,d,e,h,f,l,n,q,D,t>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,h,f,l,n,q,null)},zb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1fv(X(a),y,c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)}},Tb:(a,b)=>{O.uniform1i(X(a),
b)},vb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1iv(X(a),w,c>>2,b);else{if(288>=b)for(var d=Qb[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),d)}},yb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2fv(X(a),y,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2]}else d=y.subarray(c>>2,c+8*b>>2);O.uniform2fv(X(a),d)}},ub:(a,b,c)=>{if(2<=W.version)b&&O.uniform2iv(X(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Qb[b],e=0;e<b;e+=2)d[e]=
w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)}},xb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3fv(X(a),y,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2]}else d=y.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)}},tb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3iv(X(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Qb[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=
w.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),d)}},wb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4fv(X(a),y,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=y;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)}},sb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4iv(X(a),w,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Qb[b],e=0;e<b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2]}else d=
w.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),d)}},rb:(a,b,c,d)=>{if(2<=W.version)b&&O.uniformMatrix4fv(X(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=Y[16*b],h=y;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)}},
l:a=>{a=Q[a];O.useProgram(a);O.qd=a},Cb:(a,b)=>{O.vertexAttribDivisor(a,b)},Db:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Eb:(a,b,c,d,e,h)=>{O.vertexAttribPointer(a,b,c,!!d,e,h)},qa:(a,b,c,d)=>O.viewport(a,b,c,d),cb:Fa,Xb:function(){g.gd=a=>{0!=Zb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.gd)},Ya:function(){g.md=a=>{const b=a.clipboardData.getData("text");Vb(()=>{const c=Sb(b);Yb(c)})};window.addEventListener("paste",g.md)},Sa:function(){g.Ud=[];g.hd=
b=>{b.stopPropagation();b.preventDefault()};g.jd=b=>{b.stopPropagation();b.preventDefault()};g.kd=b=>{b.stopPropagation();b.preventDefault()};g.ld=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Vd=c;$b(c.length);for(let e=0;e<c.length;e++)Vb(()=>{const h=Sb(c[e].name);ac(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);bc(b.clientX,b.clientY,d)};const a=g.Ac;a.addEventListener("dragenter",g.hd,!1);a.addEventListener("dragleave",g.jd,
!1);a.addEventListener("dragover",g.kd,!1);a.addEventListener("drop",g.ld,!1)},Ob:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Vb:function(a){g.Jc&&(URL.revokeObjectURL(g.Jc[a].xd),g.Jc[a]=null)},Ha:function(){document.exitPointerLock&&document.exitPointerLock()},La:function(a,b){0!==b&&(document.title=b?C(v,b):"");a=a?C(v,a):"";void 0!==g.canvas&&("object"===typeof g.canvas?ab[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
g.Ac=I(a);g.Ac||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.Ac.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Wb:function(){window.removeEventListener("beforeunload",g.gd)},Ta:function(){window.removeEventListener("paste",g.md)},Qa:function(){const a=g.Ac;a.removeEventListener("dragenter",g.hd);a.removeEventListener("dragleave",g.jd);a.removeEventListener("dragover",g.kd);a.removeEventListener("drop",g.ld)},w:function(){g.Ac&&
g.Ac.requestPointerLock&&g.Ac.requestPointerLock()},Aa:function(a,b,c){if(g.Ac){if(0===b)a="none";else if(0!=c)a=g.Jc[a].zd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.Ac.style.cursor=a}},Ib:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(v.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Za:function(){return g.Bc?g.Bc.bufferSize:0},hb:function(a,b,c){g.sc=null;g.Bc=null;"undefined"!==typeof AudioContext?g.sc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.sc=null,console.log("sokol_audio.h: no WebAudio support"));
if(g.sc){console.log("sokol_audio.h: sample rate ",g.sc.sampleRate);g.Bc=g.sc.createScriptProcessor(c,0,b);g.Bc.onaudioprocess=e=>{const h=e.outputBuffer.length,f=ic(h);if(f){const l=e.outputBuffer.numberOfChannels;for(let n=0;n<l;n++){const q=e.outputBuffer.getChannelData(n);for(let t=0;t<h;t++)q[t]=y[(f>>2)+(l*t+n)]}}};g.Bc.connect(g.sc.destination);const d=()=>{if(g.sc){const e=g.sc.state;"suspended"!==e&&"interrupted"!==e||g.sc.resume().catch(()=>{console.warn("sokol_audio.h: webaudio resume failed")})}};
g.sc.onstatechange=d;document.addEventListener("visibilitychange",()=>{"visible"===document.visibilityState&&d()});document.addEventListener("click",d,{once:!0});document.addEventListener("touchend",d,{once:!0});document.addEventListener("keydown",d,{once:!0});return 1}return 0},_a:function(){return g.sc?g.sc.sampleRate:0},la:function(){const a=g.sc;null!==a&&(g.Bc&&g.Bc.disconnect(),a.close(),g.sc=null,g.Bc=null)},z:function(a,b,c,d,e,h){const f=b?C(v,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+
d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=h?(v.set(n,e),ec(a,d,n.length)):gc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);hc(a)}):fc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);hc(a)})},ma:function(a,b){const c=b?C(v,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),
hc(a)):dc(a,Number(d))):fc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);hc(a)})},ka:function(a,b){b=b?C(v,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function lc(a=[]){var b=cc;a.unshift(ea);var c=a.length,d=Rb(4*(c+1)),e=d,h;for(h of a)x[e>>2]=Sb(h),e+=4;x[e>>2]=0;try{var f=b(c,d);r=f;Fa(f)}catch(l){Ea(l)}}
function mc(a=da){function b(){g.calledRun=!0;if(!p){nc.Zb();g.onRuntimeInitialized?.();g.noInitialRun||lc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.push(c)}xa(ya)}}if(0<A)B=mc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();xa(za);0<A?B=mc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var nc;
(async function(){function a(c){c=nc=c.exports;Yb=g.__sapp_emsc_onpaste=c._b;Zb=g.__sapp_html5_get_ask_leave_site=c.$b;$b=g.__sapp_emsc_begin_drop=c.ac;ac=g.__sapp_emsc_drop=c.bc;bc=g.__sapp_emsc_end_drop=c.cc;g.__sapp_emsc_invoke_fetch_cb=c.dc;g.__sapp_emsc_set_fullscreen_flag=c.ec;cc=g._main=c.fc;dc=g.__sfetch_emsc_head_response=c.gc;ec=g.__sfetch_emsc_get_response=c.hc;fc=g.__sfetch_emsc_failed_http_status=c.ic;gc=g.__sfetch_emsc_failed_buffer_too_small=c.jc;hc=g.__sfetch_emsc_failed_other=c.kc;
ic=g.__saudio_emsc_pull=c.lc;N=c.mc;jc=c.oc;Ub=c.pc;Rb=c.qc;Tb=c.rc;oa=c.Yb;db=c.nc;na();A--;g.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return nc}A++;g.monitorRunDependencies?.(A);var b={a:kc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=g.locateFile?g.locateFile("doom.wasm",ia):ia+"doom.wasm";return a((await va(b)).instance)})();mc();
