var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),g=console.error.bind(console),n,q=!1,na,la=a=>a.startsWith("file://"),oa,r,t,pa,qa,v,w,ra,x;
function sa(){var a=oa.buffer;r=new Int8Array(a);pa=new Int16Array(a);t=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);ra=new Float32Array(a);x=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var y=0,z=null;function ta(a){f.onAbort?.(a);a="Aborted("+a+")";g(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(f)},Aa=[],Ba=[],Ca=()=>{var a=f.preRun.shift();Ba.push(a)},Da=!0,Ea=0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,C=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|k);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|h:(e&7)<<18|k<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=
65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},D={},Ga=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Da||0<Ea||(f.onExit?.(a),q=!0);fa(a,new ya(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Da||0<Ea))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!q)try{a(),Ja()}catch(b){Ga(b)}},Ra=(a,b)=>{La=a;Ma=b;if(E)if(Na||=!0,0==a)F=function(){setTimeout(G,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)F=function(){Pa(G)};else if(2==a){if("undefined"==
typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;F=function(){Qa(G)}}},$a=(a,b,c,d,e)=>{function k(){return h<Sa?(Ja(),!1):!0}E=a;Ta=d;var h=Sa;Na=!1;G=function(){if(!q)if(0<Ua.length){var l=
Ua.shift();l.pd(l.cd);if(Va){var m=Va,p=0==m%1?m-1:Math.floor(m);Va=l.ed?p:(8*m+(p+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=Va??0,p=Wa.ld??0,m?m<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));k()&&setTimeout(G,0)}else if(k())if(Xa=Xa+1|0,1==La&&1<Ma&&0!=Xa%Ma)F();else{0==La&&(Oa=performance.now());a:if(!q){for(l of Ya)if(!1===l())break a;Ka(a);for(m of Za)m()}k()&&F()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),F());if(c)throw"unwind";},Na=!1,F=
null,Sa=0,E=null,Ta=0,La=0,Ma=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){F=null;Sa++}var H=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===H)H=b+1E3/60;else for(;b+2>=H;)H+=1E3/60;setTimeout(a,Math.max(H-b,0))}}
var Wa={},Oa,G,Qa,Va,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?C(t,a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,J=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=K.ic[a];b.target.removeEventListener(b.hc,b.Kc,b.jc);K.ic.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:K.xc&&K.Yc.vc){var a=K.nc;K.nc=[];for(var b of a)b.Ac(...b.Gc)}}function L(a){if(!a.target)return-4;if(a.kc)a.Kc=function(c){++K.xc;K.Yc=a;gb();a.lc(c);gb();--K.xc},a.target.addEventListener(a.hc,a.Kc,a.jc),K.ic.push(a);else for(var b=0;b<K.ic.length;++b)K.ic[b].target==a.target&&K.ic[b].hc==a.hc&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={dd:0,qd:0,yc:0,uc:0,Ec:0,Cc:0,wc:0,jd:0,vd:0,hd:0,od:0,zc:0,Gd:0,Bc:0,sd(a,b,c){r.set(r.subarray(b,b+c),a)},xd(){for(;K.ic.length;)fb(K.ic.length-1);K.nc=[]},xc:0,nc:[],gd(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var e of K.nc)if(e.Ac==a&&d(e.Gc,c))return;K.nc.push({Ac:a,Pc:b,Gc:c});K.nc.sort((k,h)=>k.Pc<h.Pc)},zd(a){K.nc=K.nc.filter(b=>b.Ac!=a)},ic:[],yd:(a,b)=>{for(var c=0;c<K.ic.length;++c)K.ic[c].target!=a||b&&b!=K.ic[c].hc||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.codePointAt(k);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;k++}}d[b]=0;return b-
e},ib=(a,b,c,d,e,k)=>{K.wc||(K.wc=N(256));a={target:I(a),hc:k,kc:d,lc:(h=event)=>{var l=h.target.id?h.target.id:"",m=K.wc;M(hb(h.target),m+0,128);M(l,m+128,128);J(d)(e,m,b)&&h.preventDefault()},jc:c};return L(a)},jb=(a,b,c,d,e,k)=>{K.yc||(K.yc=N(160));a={target:I(a),hc:k,kc:d,lc:h=>{var l=K.yc;x[l>>3]=h.timeStamp;var m=l>>2;v[m+2]=h.location;r[l+12]=h.ctrlKey;r[l+13]=h.shiftKey;r[l+14]=h.altKey;r[l+15]=h.metaKey;r[l+16]=h.repeat;v[m+5]=h.charCode;v[m+6]=h.keyCode;v[m+7]=h.which;M(h.key||"",l+32,32);
M(h.code||"",l+64,32);M(h.char||"",l+96,32);M(h.locale||"",l+128,32);J(d)(e,l,b)&&h.preventDefault()},jc:c};return L(a)},kb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=cb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,k)=>{K.uc||(K.uc=N(64));a=I(a);return L({target:a,
vc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,hc:k,kc:d,lc:(h=event)=>{kb(K.uc,h,a);J(d)(e,K.uc,b)&&h.preventDefault()},jc:c})},lb=(a,b,c,d)=>{K.zc||(K.zc=N(257));return L({target:a,hc:"pointerlockchange",kc:d,lc:(e=event)=>{var k=K.zc,h=document.pointerLockElement;r[k]=!!h;var l=h?.id||"";M(hb(h),k+1,128);M(l,k+129,128);J(d)(20,k,b)&&e.preventDefault()},jc:c})},mb=(a,b,c,d)=>L({target:a,hc:"pointerlockerror",kc:d,lc:(e=event)=>{J(d)(38,0,b)&&e.preventDefault()},jc:c}),nb=(a,b,c,d)=>{K.Cc||
(K.Cc=N(36));a=I(a);return L({target:a,hc:"resize",kc:d,lc:(e=event)=>{if(e.target==a){var k=document.body;if(k){var h=K.Cc;v[h>>2]=0;v[h+4>>2]=k.clientWidth;v[h+8>>2]=k.clientHeight;v[h+12>>2]=innerWidth;v[h+16>>2]=innerHeight;v[h+20>>2]=outerWidth;v[h+24>>2]=outerHeight;v[h+28>>2]=pageXOffset|0;v[h+32>>2]=pageYOffset|0;J(d)(10,h,b)&&e.preventDefault()}}},jc:c})},ob=(a,b,c,d,e,k)=>{K.Bc||(K.Bc=N(1552));a=I(a);return L({target:a,vc:"touchstart"==k||"touchend"==k,hc:k,kc:d,lc:h=>{var l={},m=h.touches;
for(var p of m)p.Mc=p.Oc=0,l[p.identifier]=p;for(var u of h.changedTouches)u.Mc=1,l[u.identifier]=u;for(var A of h.targetTouches)l[A.identifier].Oc=1;m=K.Bc;x[m>>3]=h.timeStamp;r[m+12]=h.ctrlKey;r[m+13]=h.shiftKey;r[m+14]=h.altKey;r[m+15]=h.metaKey;p=m+16;u=cb(a);A=0;for(let B of Object.values(l))if(l=p>>2,v[l]=B.identifier,v[l+1]=B.screenX,v[l+2]=B.screenY,v[l+3]=B.clientX,v[l+4]=B.clientY,v[l+5]=B.pageX,v[l+6]=B.pageY,r[p+28]=B.Mc,r[p+29]=B.Oc,v[l+8]=B.clientX-(u.left|0),v[l+9]=B.clientY-(u.top|
0),p+=48,31<++A)break;v[m+8>>2]=A;J(d)(e,m,b)&&h.preventDefault()},jc:c})},P,pb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,h)=>b.drawElementsInstancedANGLE(c,d,e,k,h))},qb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},rb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},sb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},tb=1,Q=[],R=[],ub=[],S=[],T=[],U=[],vb=[],wb=[],V=[],xb={},yb=4,zb=0,Ab=a=>{for(var b=tb++,c=a.length;c<b;c++)a[c]=null;return b},X=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=P[c](),h=k&&Ab(d);k?(k.name=h,d[h]=k):W||=1282;v[b+4*e>>2]=h}},Cb=(a,b)=>{a.Lc||(a.Lc=a.getContext,a.getContext=function(d,e){e=a.Lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Nc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Bb(c,b):0},Bb=(a,b)=>{var c=Ab(wb),d={handle:c,attributes:b,version:b.Nc,Fc:a};a.canvas&&(a.canvas.bd=d);wb[c]=d;("undefined"==typeof b.Jc||b.Jc)&&Db(d);return c},Db=a=>{a||=Y;if(!a.ad){a.ad=!0;var b=a.Fc;b.ud=b.getExtension("WEBGL_multi_draw");b.nd=b.getExtension("EXT_polygon_offset_clamp");b.md=b.getExtension("EXT_clip_control");b.Hd=b.getExtension("WEBGL_polygon_mode");pb(b);qb(b);rb(b);b.kd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.rd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Ic=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ic)b.Ic=b.getExtension("EXT_disjoint_timer_query");sb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},W,Y,Eb=(a,b,c,d,e,k)=>{a={target:I(a),hc:k,kc:d,lc:(h=event)=>{J(d)(e,0,b)&&h.preventDefault()},jc:c};L(a)},Fb=(a,b,c,d)=>{K.Ec||(K.Ec=N(96));return L({target:a,vc:!0,hc:"wheel",kc:d,lc:(e=event)=>{var k=K.Ec;kb(k,e,a);x[k+64>>3]=e.deltaX;x[k+72>>3]=e.deltaY;x[k+80>>3]=e.deltaZ;
v[k+88>>2]=e.deltaMode;J(d)(9,k,b)&&e.preventDefault()},jc:c})},Gb=["default","low-power","high-performance"],Hb=[null,[],[]],Ib=[],Jb=()=>{var a=sb(P);return a=a.concat(a.map(b=>"GL_"+b))},Kb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){W||=1282;return}c=Jb().length;break;case 33307:case 33308:if(2>Y.version){W||=1280;return}c=33307==a?3:0}if(void 0===
c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:W||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=
0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W||=1280;g(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:W||=1280;g(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else W||=1281},Lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Mb=a=>{var b=Lb(a)+
1,c=N(b);c&&M(a,c,b);return c},Nb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ob=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?v:6==a?ra:5==a||28922==a||28520==a||30779==a||30782==a?w:qa},Qb=a=>{var b=Lb(a)+1,c=Pb(b);M(a,c,b);return c},Tb=a=>{var b=Rb();a();Sb(b)};f.requestAnimationFrame=Pa;f.pauseMainLoop=ab;f.resumeMainLoop=function(){Sa++;var a=La,b=Ma,c=E;E=null;$a(c,0,!1,Ta,!0);Ra(a,b);F()};f.preMainLoop&&Ya.push(f.preMainLoop);f.postMainLoop&&Za.push(f.postMainLoop);for(let a=0;32>a;++a)Ib.push(Array(a));
f.noExitRuntime&&(Da=f.noExitRuntime);f.print&&(ma=f.print);f.printErr&&(g=f.printErr);f.wasmBinary&&(n=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);
var N,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,Sb,Pb,Rb,gc={hb:()=>ta(""),$a:()=>{Da=!1;Ea=0},cb:a=>{if(ca){if(!a)return 1;a=a?C(t,a):"";if(!a.length)return 0;a=require("child_process").Ed(a,[],{Bd:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15;default:return 2}})(a.signal)):a.status<<8|0}return a?-52:0},ab:(a,b)=>{D[a]&&
(clearTimeout(D[a].id),delete D[a]);if(!b)return 0;var c=setTimeout(()=>{delete D[a];Ka(()=>fc(a,performance.now()))},b);D[a]={id:c,Fd:b};return 0},Pa:()=>{ab();E=null},ha:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ja:(a,b,c)=>{a=I(a);if(!a)return-4;a=cb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Qa:()=>performance.now(),Va:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},bb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=
c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},R:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),ga:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),$:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),Z:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),_:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),Wa:(a,b,c)=>{a=J(a);$a(a,
b,c)},fa:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),ca:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),ba:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),da:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),ea:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),U:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?lb(a,b,c,d):-4:-1,T:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?mb(a,b,c,d):-4:-1,ia:(a,b,c,d)=>nb(a,b,c,d),V:(a,b,c,d)=>ob(a,b,c,d,25,"touchcancel"),W:(a,b,c,d)=>ob(a,b,c,d,23,"touchend"),X:(a,b,c,d)=>ob(a,b,c,d,24,"touchmove"),Y:(a,
b,c,d)=>ob(a,b,c,d,22,"touchstart"),Q:(a,b,c,d)=>{Eb(a,b,c,d,31,"webglcontextlost");return 0},P:(a,b,c,d)=>{Eb(a,b,c,d,32,"webglcontextrestored");return 0},aa:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Fb(a,b,c,d):-1:-4,Ua:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Gb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Nc:v[c+4],td:v[c+5],Jc:r[b+24],$c:r[b+25],wd:v[c+7],Ad:r[b+
32]};a=I(a);return!a||b.$c?0:Cb(a,b)},Ta:a=>{Y=wb[a];f.ctx=P=Y?.Fc;return!a||P?0:-5},Lb:Ia,fb:()=>52,db:function(){return 70},gb:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var h=w[b>>2],l=w[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=a,u=t[h+m],A=Hb[p];0===u||10===u?((1===p?ma:g)(C(A)),A.length=0):A.push(u)}e+=l}w[d>>2]=e;return 0},p:a=>P.activeTexture(a),s:(a,b)=>{P.attachShader(R[a],U[b])},b:(a,b)=>{35051==a?P.Hc=b:35052==a&&(P.pc=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},pb:(a,b,c,
d,e)=>{P.bindBufferRange(a,b,Q[c],d,e)},i:(a,b)=>{P.bindFramebuffer(a,ub[b])},zb:(a,b)=>{P.bindRenderbuffer(a,S[b])},o:(a,b)=>{P.bindSampler(a,V[b])},d:(a,b)=>{P.bindTexture(a,T[b])},O:a=>{P.bindVertexArray(vb[a])},J:(a,b,c,d)=>P.blendColor(a,b,c,d),K:(a,b)=>P.blendEquationSeparate(a,b),L:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),jb:(a,b,c,d,e,k,h,l,m,p)=>P.blitFramebuffer(a,b,c,d,e,k,h,l,m,p),Da:(a,b,c,d)=>{2<=Y.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?t.subarray(c,
c+b):b,d)},D:(a,b,c,d)=>{2<=Y.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},xb:a=>P.checkFramebufferStatus(a),vb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),oa:(a,b,c)=>{P.clearBufferfv(a,b,ra,c>>2)},ub:(a,b,c)=>{P.clearBufferiv(a,b,v,c>>2)},q:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Eb:a=>{P.compileShader(U[a])},za:(a,b,c,d,e,k,h,l,m)=>{2<=Y.version?P.pc||!l?P.compressedTexSubImage2D(a,b,c,d,e,k,h,l,m):P.compressedTexSubImage2D(a,b,c,d,e,k,h,t,m,l):P.compressedTexSubImage2D(a,
b,c,d,e,k,h,t.subarray(m,m+l))},xa:(a,b,c,d,e,k,h,l,m,p,u)=>{P.pc?P.compressedTexSubImage3D(a,b,c,d,e,k,h,l,m,p,u):P.compressedTexSubImage3D(a,b,c,d,e,k,h,l,m,t,u,p)},va:()=>{var a=Ab(R),b=P.createProgram();b.name=a;b.tc=b.rc=b.sc=0;b.Dc=1;R[a]=b;return a},Gb:a=>{var b=Ab(U);U[b]=P.createShader(a);return b},G:a=>P.cullFace(a),Ga:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Hc&&(P.Hc=0),d==P.pc&&(P.pc=0))}},t:(a,b)=>{for(var c=0;c<a;++c){var d=
v[b+4*c>>2],e=ub[d];e&&(P.deleteFramebuffer(e),e.name=0,ub[d]=null)}},n:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):W||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(P.deleteRenderbuffer(e),e.name=0,S[d]=null)}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=V[d];e&&(P.deleteSampler(e),e.name=0,V[d]=null)}},l:a=>{if(a){var b=U[a];b?(P.deleteShader(b),U[a]=null):W||=1281}},j:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(P.deleteTexture(e),e.name=
0,T[d]=null)}},Fa:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];P.deleteVertexArray(vb[d]);vb[d]=null}},w:a=>P.depthFunc(a),v:a=>{P.depthMask(!!a)},e:a=>P.disable(a),M:a=>{P.disableVertexAttribArray(a)},lb:(a,b,c)=>{P.drawArrays(a,b,c)},mb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=Ib[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];P.drawBuffers(c)},nb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},ob:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},h:a=>P.enable(a),qb:a=>{P.enableVertexAttribArray(a)},
ra:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,S[d])},k:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,T[d],e)},y:(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,T[c],d,e)},H:a=>P.frontFace(a),Ea:(a,b)=>{X(a,b,"createBuffer",Q)},N:(a,b)=>{X(a,b,"createFramebuffer",ub)},Bb:(a,b)=>{X(a,b,"createRenderbuffer",S)},wa:(a,b)=>{X(a,b,"createSampler",V)},Ca:(a,b)=>{X(a,b,"createTexture",T)},Oa:(a,b)=>{X(a,b,"createVertexArray",vb)},Cb:(a,b)=>P.getAttribLocation(R[a],b?C(t,b):""),c:(a,b)=>Kb(a,b),Ib:(a,b,c,d)=>{a=
P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},z:(a,b,c)=>{if(c)if(a>=tb)W||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.tc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.tc=Math.max(a.tc,P.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.tc}else if(35722==b){if(!a.rc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.rc=Math.max(a.rc,P.getActiveAttrib(a,b).name.length+
1);v[c>>2]=a.rc}else if(35381==b){if(!a.sc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.sc=Math.max(a.sc,P.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.sc}else v[c>>2]=P.getProgramParameter(a,b);else W||=1281},Db:(a,b,c,d)=>{a=P.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},ta:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(U[a]),v[c>>2]=a?a.length+1:0):v[c>>
2]=P.getShaderParameter(U[a],b):W||=1281},La:(a,b)=>{if(2>Y.version)return W||=1282,0;var c=xb[a];if(c)return 0>b||b>=c.length?(W||=1281,0):c[b];switch(a){case 7939:return c=Jb().map(Mb),c=xb[a]=c,0>b||b>=c.length?(W||=1281,0):c[b];default:return W||=1280,0}},ua:(a,b)=>{b=b?C(t,b):"";if(a=R[a]){var c=a,d=c.qc,e=c.Xc,k;if(!d){c.qc=d={};c.Wc={};var h=P.getProgramParameter(c,35718);for(k=0;k<h;++k){var l=P.getActiveUniform(c,k);var m=l.name;l=l.size;var p=Nb(m);p=0<p?m.slice(0,p):m;var u=c.Dc;c.Dc+=
l;e[p]=[l,u];for(m=0;m<l;++m)d[u]=m,c.Wc[u++]=p}}c=a.qc;d=0;e=b;k=Nb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Xc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else W||=1281;return-1},ib:(a,b,c)=>{for(var d=Ib[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];P.invalidateFramebuffer(a,d)},A:a=>{a=R[a];P.linkProgram(a);a.qc=0;a.Xc={}},Ma:(a,b)=>{3317==a?yb=b:3314==a&&(zb=b);P.pixelStorei(a,b)},I:(a,b)=>P.polygonOffset(a,b),kb:a=>P.readBuffer(a),yb:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,
b,c,d,e),B:(a,b,c)=>{P.samplerParameterf(V[a],b,c)},g:(a,b,c)=>{P.samplerParameteri(V[a],b,c)},wb:(a,b,c,d)=>P.scissor(a,b,c,d),Fb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var h=(h=w[c+4*k>>2])?C(t,h,d?w[d+4*k>>2]:void 0):"";e+=h}P.shaderSource(U[a],e)},Ka:(a,b,c)=>P.stencilFunc(a,b,c),na:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),r:a=>P.stencilMask(a),Ia:(a,b,c)=>P.stencilOp(a,b,c),ma:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Ba:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Aa:(a,b,c,d,e,k)=>P.texStorage3D(a,
b,c,d,e,k),f:(a,b,c,d,e,k,h,l,m)=>{if(2<=Y.version){if(P.pc){P.texSubImage2D(a,b,c,d,e,k,h,l,m);return}if(m){var p=Ob(l);P.texSubImage2D(a,b,c,d,e,k,h,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(m){p=Ob(l);var u=k*((zb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[h-6402]||1)*p.BYTES_PER_ELEMENT+yb-1&-yb);m=p.subarray(m>>>31-Math.clz32(p.BYTES_PER_ELEMENT),m+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=null;P.texSubImage2D(a,b,c,d,e,k,h,l,m)},C:(a,b,c,d,e,k,h,l,m,
p,u)=>{if(P.pc)P.texSubImage3D(a,b,c,d,e,k,h,l,m,p,u);else if(u){var A=Ob(p);P.texSubImage3D(a,b,c,d,e,k,h,l,m,p,A,u>>>31-Math.clz32(A.BYTES_PER_ELEMENT))}else P.texSubImage3D(a,b,c,d,e,k,h,l,m,p,null)},Hb:(a,b)=>{var c=P,d=c.uniform1i;var e=P.Zc;if(e){var k=e.qc[a];"number"==typeof k&&(e.qc[a]=k=P.getUniformLocation(e,e.Wc[a]+(0<k?`[${k}]`:"")));a=k}else W||=1282,a=void 0;d.call(c,a,b)},m:a=>{a=R[a];P.useProgram(a);P.Zc=a},rb:(a,b)=>{P.vertexAttribDivisor(a,b)},sb:(a,b,c,d,e)=>{P.vertexAttribIPointer(a,
b,c,d,e)},tb:(a,b,c,d,e,k)=>{P.vertexAttribPointer(a,b,c,!!d,e,k)},qa:(a,b,c,d)=>P.viewport(a,b,c,d),_a:Ha,Kb:function(){f.Qc=a=>{0!=Vb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Qc)},Sa:function(){f.Vc=a=>{const b=a.clipboardData.getData("text");Tb(()=>{const c=Qb(b);Ub(c)})};window.addEventListener("paste",f.Vc)},Na:function(){f.Cd=[];f.Rc=b=>{b.stopPropagation();b.preventDefault()};f.Sc=b=>{b.stopPropagation();b.preventDefault()};f.Tc=b=>{b.stopPropagation();
b.preventDefault()};f.Uc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Dd=c;Wb(c.length);for(let e=0;e<c.length;e++)Tb(()=>{const k=Qb(c[e].name);Xb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Yb(b.clientX,b.clientY,d)};const a=f.oc;a.addEventListener("dragenter",f.Rc,!1);a.addEventListener("dragleave",f.Sc,!1);a.addEventListener("dragover",f.Tc,!1);a.addEventListener("drop",f.Uc,!1)},Jb:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},ya:function(){document.exitPointerLock&&document.exitPointerLock()},Ha:function(a,b){0!==b&&(document.title=b?C(t,b):"");a=a?C(t,a):"";void 0!==f.canvas&&("object"===typeof f.canvas?bb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.oc=I(a);f.oc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.oc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Xa:function(){window.removeEventListener("beforeunload",
f.Qc)},Ra:function(){window.removeEventListener("paste",f.Vc)},Ja:function(){const a=f.oc;a.removeEventListener("dragenter",f.Rc);a.removeEventListener("dragleave",f.Sc);a.removeEventListener("dragover",f.Tc);a.removeEventListener("drop",f.Uc)},u:function(){f.oc&&f.oc.requestPointerLock&&f.oc.requestPointerLock()},Ab:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,0,
0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ya:function(){return f.mc?f.mc.bufferSize:0},eb:function(a,b,c){f.fc=null;f.mc=null;"undefined"!==typeof AudioContext?f.fc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.fc=null,console.log("sokol_audio.h: no WebAudio support"));return f.fc?(console.log("sokol_audio.h: sample rate ",f.fc.sampleRate),f.mc=f.fc.createScriptProcessor(c,0,b),f.mc.onaudioprocess=
d=>{const e=d.outputBuffer.length,k=ec(e);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=ra[(k>>2)+(h*p+l)]}}},f.mc.connect(f.fc.destination),a=()=>{f.fc&&"suspended"===f.fc.state&&f.fc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Za:function(){return f.fc?f.fc.sampleRate:0},la:function(){const a=
f.fc;null!==a&&(f.mc&&f.mc.disconnect(),a.close(),f.fc=null,f.mc=null)},x:function(a,b,c,d,e,k){const h=b?C(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(h,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=k?(t.set(m,e),ac(a,d,m.length)):cc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,m);dc(a)}):bc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,l);dc(a)})},pa:function(a,b){const c=
b?C(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),dc(a)):$b(a,Number(d))):bc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);dc(a)})},ka:function(a,b){b=b?C(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Mb;sa();eb=Z.ac;c=Z;N=c.Ob;f.__sapp_emsc_onpaste=Ub=c.Pb;f.__sapp_html5_get_ask_leave_site=Vb=c.Qb;f.__sapp_emsc_begin_drop=Wb=c.Rb;f.__sapp_emsc_drop=Xb=c.Sb;f.__sapp_emsc_end_drop=Yb=c.Tb;f.__sapp_emsc_invoke_fetch_cb=c.Ub;f._main=Zb=c.Vb;f.__sfetch_emsc_head_response=$b=c.Wb;f.__sfetch_emsc_get_response=ac=c.Xb;f.__sfetch_emsc_failed_http_status=bc=c.Yb;f.__sfetch_emsc_failed_buffer_too_small=cc=c.Zb;f.__sfetch_emsc_failed_other=dc=c._b;f.__saudio_emsc_pull=
ec=c.$b;fc=c.bc;Sb=c.cc;Pb=c.dc;Rb=c.ec;y--;f.monitorRunDependencies?.(y);0==y&&z&&(c=z,z=null,c());return Z}y++;f.monitorRunDependencies?.(y);var b={a:gc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=f.locateFile?f.locateFile("doom.wasm",ia):ia+"doom.wasm";return a((await xa(b)).instance)})();
function hc(a=[]){var b=Zb;a.unshift(ea);var c=a.length,d=Pb(4*(c+1)),e=d;a.forEach(h=>{w[e>>2]=Qb(h);e+=4});w[e>>2]=0;try{var k=b(c,d);Ia(k,!0)}catch(h){Ga(h)}}
function ic(a=da){function b(){f.calledRun=!0;if(!q){Z.Nb();f.onRuntimeInitialized?.();f.noInitialRun||hc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();Aa.push(c)}za(Aa)}}if(0<y)z=ic;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();za(Ba);0<y?z=ic:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();ic();
